version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Create .env file
                command: touch .env
            - run:
                name: Build Containers
                command: docker-compose build
            - run:
                name: Run Postgres
                command: docker-compose up -d db
    test:
        machine: true
        steps:
            - checkout 
            - run:
                name: Run Tests
                command: docker-compose run pytest tests/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build